import { createSlice } from "@reduxjs/toolkit";
import allModules from "../../components/pages/NewUser/AllModules";

const initialState = {
    user_auth: {
        loggedIn: false,
        userType: "admin",
        username: null,
        loginTimestamp: null
    },
    userModules: allModules,
};


const authSlice = createSlice({
    name: "authSlice",
    initialState: initialState,
    reducers: {
        userLoggedIn: (state, action) => {
            const userDetails = {
                loggedIn: action.payload.status,
                userType: action.payload.access,
                username: action.payload.username,
                logoutTimestamp: Date.now()
            };
            localStorage.setItem("user", JSON.stringify(userDetails));
            state.user_auth = userDetails;
        },
        userLoggedOut: (state) => {
            const userDetails = {
                loggedIn: false,
                userType: null,
            };
            localStorage.setItem("user", JSON.stringify(userDetails));
            state.user_auth = userDetails;
        },

        // Assign Modules
        updateModules: (state, action) => {
            const { moduleName, moduleSelected } = action.payload;

            const updatedModules = [];
            state.userModules.map((module, moduleKey) => {
                updatedModules.push(module);
                if(module.moduleName === action.payload.moduleName){
                    updatedModules[moduleKey] = action.payload;
                }
            })
            state.userModules = updatedModules;
            // console.log(action.payload)
            console.log(updatedModules)
        },


        resetModules: (state, action) => {
            state.userModules = allModules;
            // console.log(action.payload)
        }
    }
});










// Export the actions generated by createSlice
export const {  userLoggedIn, userLoggedOut, updateModules, resetModules } = authSlice.actions;

// Export the reducer to be added to the store
export default authSlice.reducer;